name: Publier l'application

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Préparer GitHub Pages
        uses: actions/configure-pages@v5

      - name: Préparer les fichiers du site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Mettre le site en ligne
        id: deployment
        uses: actions/deploy-pages@v4
